// LeetCode 389
// You are given two strings s and t.
// String t is generated by random shuffling string s and then add 
// one more letter at a random position.
// Return the letter that was added to t

package LeetCodeSolutions;

public class FindDifference {
    public static char FindDifference(String s, String t){
        char c = 0;
        char[] S = s.toCharArray();
        char[] T = t.toCharArray();

        for(int i =0; i<S.length; i++){
            c ^=S[i];
        }
        for(int i =0; i<T.length; i++){
            c ^=T[i];
        }
        return c;
    }
    public static void main(String[] args) {
        String s = "abcd";
        String t = "dckba";
        System.out.println("Character added :"+FindDifference(s, t));
    }
    
}
